server:
    error:
        include-stacktrace: on-param
        
spring:
    datasource:
        url: jdbc:mysql://localhost:3307/anime?createDatabaseIfNotExist=true
        username: root
        password: rafa9898
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true